import type { Metadata, Viewport } from "next";
import "./globals.css";

/**
 * viewport export — Next.js emits this as the <meta name="theme-color"> and
 * <meta name="viewport"> tags. Safari reads theme-color from here (it ignores
 * manifest theme_color). viewportFit="cover" is required so that
 * env(safe-area-inset-*) values are non-zero under the black-translucent
 * status bar. maximumScale=1 prevents the iOS zoom-on-input jump.
 * (FR-037, output-rendering.md § iOS-specific head tags)
 */
export const viewport: Viewport = {
  themeColor: "#0B0E14",
  viewportFit: "cover",
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

/**
 * metadata export — appleWebApp.capable adds <meta name="apple-mobile-web-app-capable">
 * which, combined with iOS 26's default standalone behaviour, launches the app
 * edge-to-edge. statusBarStyle "black-translucent" lets the app draw under the
 * status bar; headers must compensate with padding-top: env(safe-area-inset-top).
 * startupImage: T-063 [HUMAN] must fill in the ~25 device-size PNG entries using
 * pwa-asset-generator output (see output-rendering.md § Performance Optimization #7).
 * (FR-037, output-rendering.md § iOS-specific head tags)
 */
export const metadata: Metadata = {
  title: "Financify",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Financify",
    // T-063 [HUMAN]: replace this empty array with the ~25 apple-touch-startup-image
    // entries generated by pwa-asset-generator from the dark #0B0E14 brand frame.
    startupImage: [],
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>{children}</body>
    </html>
  );
}
